# Generated by Django 2.2.13 on 2021-04-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinus',
            name='user_id',
        ),
    ]
