# Generated by Django 3.2.3 on 2021-08-15 12:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quidroo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=90, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telephone number')),
                ('company', models.CharField(blank=True, max_length=15, verbose_name='Company')),
                ('type_business', models.CharField(blank=True, max_length=15, verbose_name='Type of Business')),
                ('address', models.CharField(blank=True, max_length=15, verbose_name='Company Address')),
                ('confirm_female_cofounder', models.CharField(blank=True, max_length=15, verbose_name='Is there atleast one female cofounder/owner')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Prospective Users Data',
            },
        ),
    ]
