# Generated by Django 3.2.3 on 2021-08-15 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_quidroo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quidroo',
            name='address',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='quidroo',
            name='company',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='quidroo',
            name='confirm_female_cofounder',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Is there atleast one female cofounder/owner'),
        ),
        migrations.AlterField(
            model_name='quidroo',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='quidroo',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='quidroo',
            name='phone',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Telephone number'),
        ),
        migrations.AlterField(
            model_name='quidroo',
            name='type_business',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Type of Business'),
        ),
    ]
